### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [AEBilgrau/GMCM#12]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by AEBilgrau** [comment]
The license is found in the `DESCRIPTION` file.

**Comment by karan** [comment]
Aha! Unusual place, but that works. Thanks @AEBilgrau.

**Comment by AEBilgrau** [comment]
Yes, somewhat unusual. But all (properly formatted) packages for the statistical language "R" will have this. 

A "DESCRIPTION" file with the line "License: <license>".

Perhaps your bot should also check that? Or maybe not, I guess this is only concerns comparatively very few repos.

Regards

**Comment by karan** [comment]
Yeah. I should check that too. Thanks for being cool. :smile:
